// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1lBEJ-iOVqQ6gwottODdo5rzhfzZ7kTg',
    appId: '1:45023907275:web:d1d41af51a81ca37f4fa4e',
    messagingSenderId: '45023907275',
    projectId: 'flutterdemo-57d17',
    authDomain: 'flutterdemo-57d17.firebaseapp.com',
    storageBucket: 'flutterdemo-57d17.appspot.com',
    measurementId: 'G-VEV0BJ8P41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbsqH-pUl2rC13e7B3X6MtGt4_s1cj374',
    appId: '1:45023907275:android:67ce8e1823c36502f4fa4e',
    messagingSenderId: '45023907275',
    projectId: 'flutterdemo-57d17',
    storageBucket: 'flutterdemo-57d17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1QxlVSMF3ejstbvGjTzD-nLnR3gImUyU',
    appId: '1:45023907275:ios:b02f2fc98ae741c1f4fa4e',
    messagingSenderId: '45023907275',
    projectId: 'flutterdemo-57d17',
    storageBucket: 'flutterdemo-57d17.appspot.com',
    iosBundleId: 'com.example.firstFlutterDemoApp',
  );
}
